FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.2

ENV discovery.type=single-node
ENV xpack.security.enabled=true

EXPOSE 9200

RUN bin/elasticsearch-users useradd kibana_user -p kibana -r kibana_system
RUN bin/elasticsearch-users useradd fluentd -p fluentd -r superuser
RUN bin/elasticsearch-users useradd logstash_user -p logstash -r superuser